### ISSUE TITLE
Feature Request: start a devbox shell for action

### ISSUE THREAD

**Issue by altano** [jetpack-io/devbox-install-action#40]
I don't know if this is possible, but it would be nice if this action started a devbox shell so that we can run:

`some-command` instead of `devbox run some-command`

**Comment by LucilleH** [comment]
I think this has been a struggle to standardize a solution that works for all. But in case your use case is simple, there's an interesting solution suggested here: https://github.com/jetpack-io/devbox-install-action/pull/25#discussion_r1491637940

**Comment by altano** [comment]
I didn't find that issue when searching, but it looks to be basically the same request, so I'm going to close this issue and keep the discussion there. Thanks for the pointer!
